kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: appdev-admins
  namespace: appdev
subjects:
  - kind: Group
    name: appdev
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: namespace-admin
  apiGroup: rbac.authorization.k8s.io